"""Everything that talks to yt-dlp for *discovery* (no downloading here)."""
from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any, Optional
from urllib.parse import parse_qs, urlparse

from yt_dlp import YoutubeDL
from yt_dlp.utils import DownloadError

from .config import config

VIDEO_ID_RE = re.compile(r"^[A-Za-z0-9_-]{11}$")

KIND_VIDEO = "video"
KIND_PLAYLIST = "playlist"
KIND_CHANNEL = "channel"


class ProbeError(RuntimeError):
    pass


# --------------------------------------------------------------------------
# URL classification
# --------------------------------------------------------------------------
def classify(raw: str) -> dict[str, Any]:
    """Work out what a pasted string points at, without hitting the network."""
    raw = (raw or "").strip()
    if not raw:
        raise ProbeError("No URL supplied.")

    # A bare video id is a common paste.
    if VIDEO_ID_RE.match(raw):
        return {"kind": KIND_VIDEO, "url": f"https://www.youtube.com/watch?v={raw}",
                "video_id": raw, "playlist_url": None}

    if not raw.startswith(("http://", "https://")):
        raw = "https://" + raw

    p = urlparse(raw)
    host = (p.hostname or "").lower().removeprefix("www.").removeprefix("m.")
    path = p.path.rstrip("/")
    qs = parse_qs(p.query)
    list_id = (qs.get("list") or [None])[0]

    if host in ("youtu.be",):
        vid = path.lstrip("/").split("/")[0]
        return {"kind": KIND_VIDEO, "url": f"https://www.youtube.com/watch?v={vid}",
                "video_id": vid,
                "playlist_url": _playlist_url(list_id)}

    if host not in ("youtube.com", "music.youtube.com", "youtubekids.com"):
        # Let yt-dlp try anyway — it supports far more than YouTube.
        return {"kind": KIND_VIDEO, "url": raw, "video_id": None, "playlist_url": None}

    if path.startswith("/playlist"):
        if not list_id:
            raise ProbeError("Playlist URL is missing its ?list= parameter.")
        return {"kind": KIND_PLAYLIST, "url": _playlist_url(list_id),
                "video_id": None, "playlist_url": None}

    if path.startswith("/watch"):
        vid = (qs.get("v") or [None])[0]
        if not vid:
            raise ProbeError("Watch URL is missing its ?v= parameter.")
        return {"kind": KIND_VIDEO, "url": f"https://www.youtube.com/watch?v={vid}",
                "video_id": vid, "playlist_url": _playlist_url(list_id)}

    for prefix in ("/shorts/", "/live/", "/embed/", "/v/"):
        if path.startswith(prefix):
            vid = path[len(prefix):].split("/")[0]
            return {"kind": KIND_VIDEO, "url": f"https://www.youtube.com/watch?v={vid}",
                    "video_id": vid, "playlist_url": _playlist_url(list_id)}

    if path.startswith("/@") or path.startswith(("/channel/", "/c/", "/user/")):
        return {"kind": KIND_CHANNEL, "url": channel_tab_url(f"https://www.youtube.com{path}"),
                "video_id": None, "playlist_url": None}

    if list_id:
        return {"kind": KIND_PLAYLIST, "url": _playlist_url(list_id),
                "video_id": None, "playlist_url": None}

    raise ProbeError(f"Could not work out what kind of YouTube URL this is: {raw}")


def _playlist_url(list_id: Optional[str]) -> Optional[str]:
    if not list_id or list_id.startswith(("RD", "UL", "LL")):
        return None  # radio / autogenerated mixes are not real playlists
    return f"https://www.youtube.com/playlist?list={list_id}"


def channel_tab_url(base: str, tab: str = "videos") -> str:
    base = base.rstrip("/")
    for suffix in ("/videos", "/shorts", "/streams", "/featured", "/playlists"):
        if base.endswith(suffix):
            base = base[: -len(suffix)]
            break
    return f"{base}/{tab}"


# --------------------------------------------------------------------------
# yt-dlp option builders
# --------------------------------------------------------------------------
def _base_opts() -> dict[str, Any]:
    opts: dict[str, Any] = {
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        "ignoreerrors": True,
        "skip_download": True,
        "socket_timeout": 30,
        "retries": 3,
        "extractor_args": {"youtubetab": {"approximate_date": ["timestamp"]}},
    }
    if config.COOKIES_FILE:
        opts["cookiefile"] = config.COOKIES_FILE
    return opts


# --------------------------------------------------------------------------
# normalisation
# --------------------------------------------------------------------------
def _thumb(entry: dict, video_id: str | None) -> str:
    thumbs = entry.get("thumbnails") or []
    best = ""
    for t in thumbs:
        url = t.get("url") or ""
        if not url:
            continue
        w = t.get("width") or 0
        if 200 <= w <= 800:
            return url
        best = best or url
    if video_id:
        return f"https://i.ytimg.com/vi/{video_id}/mqdefault.jpg"
    return best


def _upload_date(entry: dict) -> str:
    d = entry.get("upload_date")
    if d:
        return str(d)
    ts = entry.get("timestamp") or entry.get("release_timestamp")
    if ts:
        try:
            return datetime.fromtimestamp(int(ts), tz=timezone.utc).strftime("%Y%m%d")
        except (OverflowError, OSError, ValueError):
            return ""
    return ""


def normalize(entry: dict, fallback_channel: dict | None = None) -> dict[str, Any]:
    fallback_channel = fallback_channel or {}
    vid = entry.get("id") or ""
    channel_name = (
        entry.get("channel") or entry.get("uploader")
        or fallback_channel.get("channel_name") or "Unknown Channel"
    )
    channel_id = (
        entry.get("channel_id") or entry.get("uploader_id")
        or fallback_channel.get("channel_id") or f"name:{channel_name}"
    )
    channel_url = (
        entry.get("channel_url") or entry.get("uploader_url")
        or fallback_channel.get("channel_url") or ""
    )
    return {
        "video_id": vid,
        "url": entry.get("webpage_url") or entry.get("url")
               or f"https://www.youtube.com/watch?v={vid}",
        "title": entry.get("title") or "Untitled",
        "description": entry.get("description") or "",
        "duration": int(entry.get("duration") or 0),
        "upload_date": _upload_date(entry),
        "thumbnail": _thumb(entry, vid),
        "channel_name": channel_name,
        "channel_id": channel_id,
        "channel_url": channel_url,
        "view_count": entry.get("view_count") or 0,
        "is_live": bool(entry.get("is_live") or entry.get("live_status") == "is_live"),
    }


# --------------------------------------------------------------------------
# probes
# --------------------------------------------------------------------------
def probe_video(url: str) -> dict[str, Any]:
    opts = _base_opts() | {"noplaylist": True}
    try:
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
    except DownloadError as exc:
        raise ProbeError(_clean(str(exc))) from exc
    if not info:
        raise ProbeError("yt-dlp returned nothing for that video.")
    if info.get("_type") == "playlist":
        entries = [e for e in (info.get("entries") or []) if e]
        if not entries:
            raise ProbeError("That link resolved to an empty playlist.")
        info = entries[0]
    return normalize(info)


def probe_collection(url: str, limit: int | None = None) -> dict[str, Any]:
    """Flat-extract a playlist or channel tab. Cheap: one request per page."""
    limit = limit or config.PROBE_LIMIT
    opts = _base_opts() | {
        "extract_flat": "in_playlist",
        "playlistend": max(1, int(limit)),
    }
    try:
        with YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
    except DownloadError as exc:
        raise ProbeError(_clean(str(exc))) from exc
    if not info:
        raise ProbeError("yt-dlp returned nothing for that URL.")

    raw_entries = [e for e in (info.get("entries") or []) if e]
    # A bare channel URL can come back as a list of tabs; flatten one level.
    if raw_entries and all(e.get("_type") == "playlist" for e in raw_entries):
        flattened: list[dict] = []
        for tab in raw_entries:
            flattened.extend([e for e in (tab.get("entries") or []) if e])
        raw_entries = flattened

    container = {
        "channel_name": info.get("channel") or info.get("uploader") or info.get("title"),
        "channel_id": info.get("channel_id") or info.get("uploader_id"),
        "channel_url": info.get("channel_url") or info.get("uploader_url") or url,
    }
    videos = [
        normalize(e, container) for e in raw_entries
        if e.get("id") and e.get("_type") in (None, "url", "video")
    ]
    videos = [v for v in videos if v["video_id"]][: int(limit)]

    return {
        "kind": KIND_PLAYLIST if "playlist?" in url else KIND_CHANNEL,
        "title": info.get("title") or container["channel_name"] or "Results",
        "url": info.get("webpage_url") or url,
        "channel_name": container["channel_name"] or "Unknown Channel",
        "channel_id": container["channel_id"] or "",
        "channel_url": container["channel_url"] or "",
        "count": info.get("playlist_count") or len(videos),
        "videos": videos,
    }


def channel_recent(channel_url: str, limit: int | None = None,
                   exclude: str | None = None) -> list[dict[str, Any]]:
    """Latest uploads from a channel, for the 'more from this channel' panel."""
    limit = limit or config.CHANNEL_PANEL_LIMIT
    if not channel_url:
        return []
    try:
        result = probe_collection(channel_tab_url(channel_url), limit=limit + 1)
    except ProbeError:
        return []
    vids = [v for v in result["videos"] if v["video_id"] != exclude]
    return vids[:limit]


def _clean(message: str) -> str:
    message = re.sub(r"\x1b\[[0-9;]*m", "", message)
    message = message.replace("ERROR: ", "").strip()
    return message.splitlines()[0][:400] if message else "Unknown yt-dlp error"
